### ISSUE TITLE
Error when building Docker image

### ISSUE THREAD

**Issue by mikey-jay** [orden-gg/fireball#187]
Docker build fails- seems to be related to node-gyp. When I tried adding Python to the Dockerfile using "apk add", this did resolve the error, but then "make" was also required. Added that as well, but then node-gyp fails to build due to an additional error and I got stuck and was unable to resolve that error.

Output below:

--

```
[+] Building 78.4s (12/14)                                                                                                              
 => [internal] load build definition from Dockerfile                                                                               0.0s
 => => transferring dockerfile: 480B                                                                                               0.0s
 => [internal] load .dockerignore                                                                                                  0.0s
 => => transferring context: 2B                                                                                                    0.0s
 => [internal] load metadata for docker.io/library/nginx:alpine                                                                    0.7s
 => [internal] load metadata for docker.io/library/node:17-alpine                                                                  0.7s
 => [react-build 1/5] FROM docker.io/library/node:17-alpine@sha256:6f8ae702a7609f6f18d81ac72998e5d6f5d0ace9a13b866318c76340c6d986  0.0s
 => [internal] load build context                                                                                                 14.5s
 => => transferring context: 392.08MB                                                                                             14.4s
 => [stage-1 1/4] FROM docker.io/library/nginx:alpine@sha256:da9c94bec1da829ebd52431a84502ec471c8e548ffb2cedbf36260fd9bd1d4d3      0.0s
 => CACHED [react-build 2/5] WORKDIR /app                                                                                          0.0s
 => CACHED [stage-1 2/4] COPY nginx.conf /etc/nginx/conf.d/configfile.template                                                     0.0s
 => CACHED [stage-1 3/4] RUN sh -c "envsubst '$PORT'  < /etc/nginx/conf.d/configfile.template > /etc/nginx/conf.d/default.conf"    0.0s
 => [react-build 3/5] COPY . ./                                                                                                    4.3s
 => ERROR [react-build 4/5] RUN yarn                                                                                              58.8s
------                                                                                                                                  
 > [react-build 4/5] RUN yarn:                                                                                                          
#12 0.380 yarn install v1.22.17                                                                                                         
#12 0.468 [1/4] Resolving packages...                                                                                                   
#12 0.581 warning Resolution field "immer@9.0.6" is incompatible with requested version "immer@8.0.1"                                   
#12 0.643 warning Resolution field "glob-parent@5.1.2" is incompatible with requested version "glob-parent@^3.1.0"                      
#12 0.827 [2/4] Fetching packages...
#12 39.70 [3/4] Linking dependencies...
#12 39.71 warning "@emotion/css > @emotion/babel-plugin@11.3.0" has unmet peer dependency "@babel/core@^7.0.0".
#12 39.71 warning "@emotion/css > @emotion/babel-plugin > @babel/plugin-syntax-jsx@7.16.7" has unmet peer dependency "@babel/core@^7.0.0-0".
#12 39.71 warning " > @ion-phaser/react@1.3.0" has incorrect peer dependency "react@^16.7.0".
#12 39.71 warning " > @ion-phaser/react@1.3.0" has incorrect peer dependency "react-dom@^16.7.0".
#12 39.71 warning " > @testing-library/user-event@12.8.3" has unmet peer dependency "@testing-library/dom@>=7.21.4".
#12 39.71 warning " > react-data-components@1.2.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0-0".
#12 39.71 warning " > @babel/preset-env@7.16.5" has unmet peer dependency "@babel/core@^7.0.0-0".
#12 39.71 warning " > @babel/preset-react@7.16.5" has unmet peer dependency "@babel/core@^7.0.0-0".
#12 39.71 warning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
#12 57.40 [4/4] Building fresh packages...
#12 58.57 error /app/node_modules/bufferutil: Command failed.
#12 58.57 Exit code: 1
#12 58.57 Command: node-gyp-build
#12 58.57 Arguments: 
#12 58.57 Directory: /app/node_modules/bufferutil
#12 58.57 Output:
#12 58.57 gyp info it worked if it ends with ok
#12 58.57 gyp info using node-gyp@8.4.1
#12 58.57 gyp info using node@17.4.0 | linux | arm64
#12 58.57 gyp ERR! find Python 
#12 58.57 gyp ERR! find Python Python is not set from command line or npm configuration
#12 58.57 gyp ERR! find Python Python is not set from environment variable PYTHON
#12 58.57 gyp ERR! find Python checking if "python3" can be used
#12 58.57 gyp ERR! find Python - "python3" is not in PATH or produced an error
#12 58.57 gyp ERR! find Python checking if "python" can be used
#12 58.57 gyp ERR! find Python - "python" is not in PATH or produced an error
#12 58.57 gyp ERR! find Python 
#12 58.57 gyp ERR! find Python **********************************************************
#12 58.57 gyp ERR! find Python You need to install the latest version of Python.
#12 58.57 gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
#12 58.57 gyp ERR! find Python you can try one of the following options:
#12 58.57 gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
#12 58.57 gyp ERR! find Python   (accepted by both node-gyp and npm)
#12 58.57 gyp ERR! find Python - Set the environment variable PYTHON
#12 58.57 gyp ERR! find Python - Set the npm configuration variable python:
#12 58.57 gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
#12 58.57 gyp ERR! find Python For more information consult the documentation at:
#12 58.57 gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
#12 58.57 gyp ERR! find Python **********************************************************
#12 58.57 gyp ERR! find Python 
#12 58.57 gyp ERR! configure error 
#12 58.57 gyp ERR! stack Error: Could not find any Python installation to use
#12 58.57 gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
#12 58.57 gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
#12 58.57 gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
#12 58.57 gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
#12 58.57 gyp ERR! stack     at exithandler (node:child_process:406:5)
#12 58.57 gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:418:5)
#12 58.57 gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
#12 58.57 gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
#12 58.57 gyp ERR! stack     at onErrorNT (node:internal/child_process:476:16)
#12 58.57 gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
#12 58.57 gyp ERR! System Linux 5.10.76-linuxkit
#12 58.57 gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
#12 58.57 gyp ERR! cwd /app/node_modules/bufferutil
#12 58.57 gyp ERR! node -v v17.4.0
#12 58.57 gyp ERR! node-gyp -v v8.4.1
#12 58.57 gyp ERR! not ok
#12 58.57 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
executor failed running [/bin/sh -c yarn]: exit code: 1
```

**Comment by dudendy** [comment]
@mikey-jay if this is still relevant to you please discuss the issue in our discord https://discord.com/invite/orden
